### PR TITLE
Ft daniel refactor

### PR DESCRIPTION
**Pull request by DannyMichaels**
this feature updates `header.jsx` and `manageaccount.jsx` , it replaces the boolean, instead of checking if object.keys of loggedInUser doesn't equal to 0, we just check if we have a loggedInUser._id, it does the same thing, but I think it's more readable and it's the more right approach, opinion?

### CODE REVIEW

**Review by DannyMichaels — COMMENTED** [review]
all the other editions in the other pages are just my linter setting single quotes to double quotes, and fixing some spaces, I didn't want to do that but I guess it did that for me.

**Comment by DannyMichaels** [comment]
Also I'm not sure if this is the right approach actually, it works either way, but the reason we used " if object.keys" is because logged in user is set to an empty object.

The reason why I used if current user.ID in "Care" is because current user is set to null, it works either way. If we want to. We can set the user to null instead of an empty object and then that refactoring will actually make sense. Works either way anyways.

**Comment by DannyMichaels** [comment]
changed the loggedInUser set to null instead of an empty object, so now this approach actually makes sense, it's up to you, it's less lines of code and more readable, BUT, they both work the same, so if it really matters is up to you.

**Review by allicue — APPROVED** [review]
Looks good to me! Thanks Daniel

**Pull request merged**
